/* 
 * BoldSign API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

namespace BoldSign.Api
{
    using Newtonsoft.Json.Converters;

    /// <summary>
    ///     Formatter for 'date' openapi formats ss defined by full-date - RFC3339
    ///     see https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#data-types
    /// </summary>
    internal class OpenAPIDateConverter : IsoDateTimeConverter
    {
        /// <summary>
        ///     Initializes a new instance of the <see cref="OpenAPIDateConverter" /> class.
        /// </summary>
        internal OpenAPIDateConverter() =>
            // full-date   = date-fullyear "-" date-month "-" date-mday
            this.DateTimeFormat = "yyyy-MM-dd";
    }
}
