/* 
 * BoldSign API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

namespace BoldSign.Model
{
    using System;
    using System.Linq;
    using System.IO;
    using System.Text;
    using System.Text.RegularExpressions;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Runtime.Serialization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.ComponentModel.DataAnnotations;

    /// <summary>
    /// Defines ActivityAction
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum ActivityAction
    {
        /// <summary>
        /// Enum Viewed for value: Viewed
        /// </summary>
        [EnumMember(Value = "Viewed")]
        Viewed = 1,
        /// <summary>
        /// Enum Signed for value: Signed
        /// </summary>
        [EnumMember(Value = "Signed")]
        Signed = 2,
        /// <summary>
        /// Enum Reassigned for value: Reassigned
        /// </summary>
        [EnumMember(Value = "Reassigned")]
        Reassigned = 3,
        /// <summary>
        /// Enum Declined for value: Declined
        /// </summary>
        [EnumMember(Value = "Declined")]
        Declined = 4,
        /// <summary>
        /// Enum Revoked for value: Revoked
        /// </summary>
        [EnumMember(Value = "Revoked")]
        Revoked = 5,
        /// <summary>
        /// Enum Expired for value: Expired
        /// </summary>
        [EnumMember(Value = "Expired")]
        Expired = 6,
        /// <summary>
        /// Enum Downloaded for value: Downloaded
        /// </summary>
        [EnumMember(Value = "Downloaded")]
        Downloaded = 7,
        /// <summary>
        /// Enum DownloadedForPrintSign for value: DownloadedForPrintSign
        /// </summary>
        [EnumMember(Value = "DownloadedForPrintSign")]
        DownloadedForPrintSign = 8,
        /// <summary>
        /// Enum InitiatePrintAndSign for value: InitiatePrintAndSign
        /// </summary>
        [EnumMember(Value = "InitiatePrintAndSign")]
        InitiatePrintAndSign = 9,
        /// <summary>
        /// Enum InitiateFormSign for value: InitiateFormSign
        /// </summary>
        [EnumMember(Value = "InitiateFormSign")]
        InitiateFormSign = 10,
        /// <summary>
        /// Enum CancelPrintAndSign for value: CancelPrintAndSign
        /// </summary>
        [EnumMember(Value = "CancelPrintAndSign")]
        CancelPrintAndSign = 11,
        /// <summary>
        /// Enum CompletePrintAndSign for value: CompletePrintAndSign
        /// </summary>
        [EnumMember(Value = "CompletePrintAndSign")]
        CompletePrintAndSign = 12,
        /// <summary>
        /// Enum Reviewed for value: Reviewed
        /// </summary>
        [EnumMember(Value = "Reviewed")]
        Reviewed = 13,
        /// <summary>
        /// Enum None for value: None
        /// </summary>
        [EnumMember(Value = "None")]
        None = 14
    }
}
