/* 
 * BoldSign API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

namespace BoldSign.Model
{
    using System.Runtime.Serialization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    /// <summary>
    ///     Defines ReminderType
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum ReminderType
    {
        /// <summary>
        ///     Enum EveryDay for value: EveryDay
        /// </summary>
        [EnumMember(Value = "EveryDay")]
        EveryDay = 1,

        /// <summary>
        ///     Enum EveryTwoDays for value: EveryTwoDays
        /// </summary>
        [EnumMember(Value = "EveryTwoDays")]
        EveryTwoDays = 2,

        /// <summary>
        ///     Enum EveryThreeDays for value: EveryThreeDays
        /// </summary>
        [EnumMember(Value = "EveryThreeDays")]
        EveryThreeDays = 3,

        /// <summary>
        ///     Enum EveryWeek for value: EveryWeek
        /// </summary>
        [EnumMember(Value = "EveryWeek")]
        EveryWeek = 4,
    }
}
