/* 
 * BoldSign API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

namespace BoldSign.Client
{
    /// <summary>
    ///     <see cref="GlobalConfiguration" /> provides a compile-time extension point for globally configuring
    ///     API Clients.
    /// </summary>
    /// <remarks>
    ///     A customized implementation via partial class may reside in another file and may
    ///     be excluded from automatic generation via a .openapi-generator-ignore file.
    /// </remarks>
    public class GlobalConfiguration : Configuration
    {
    }
}
