//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoldSign.Api.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApiValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApiValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BoldSign.Api.Resources.ApiValidationMessages", typeof(ApiValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccessCode must be null or empty when authentication type is EmailOTP.
        /// </summary>
        internal static string AccessCodePropertyNoRequired {
            get {
                return ResourceManager.GetString("AccessCodePropertyNoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccessCode cannot be null or empty when authentication type is AccessCode.
        /// </summary>
        internal static string AccessCodePropertyRequired {
            get {
                return ResourceManager.GetString("AccessCodePropertyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;AllowFieldConfiguration&apos; property is unsupported for the Reviewer role..
        /// </summary>
        internal static string AllowConfigureFieldsError {
            get {
                return ResourceManager.GetString("AllowConfigureFieldsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Attachment Information is required..
        /// </summary>
        internal static string AttachmentInformationRequired {
            get {
                return ResourceManager.GetString("AttachmentInformationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide the Attachment Title..
        /// </summary>
        internal static string AttachmentTitleRequired {
            get {
                return ResourceManager.GetString("AttachmentTitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MinDate and MaxDate value is required.
        /// </summary>
        internal static string BothFieldsRequired {
            get {
                return ResourceManager.GetString("BothFieldsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflicting file information detected. Please use either the &apos;Files&apos; option to send a file or the &apos;FileUrls&apos; option to give a file link. Using both options at the same time is not possible..
        /// </summary>
        internal static string BothFileParamUsed {
            get {
                return ResourceManager.GetString("BothFileParamUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both HyperlinkText and value is required for Hyperlink FormField.
        /// </summary>
        internal static string BothHyperlinkFieldsRequired {
            get {
                return ResourceManager.GetString("BothHyperlinkFieldsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bounds is a required property for FormField and cannot be null.
        /// </summary>
        internal static string BoundsRequired {
            get {
                return ResourceManager.GetString("BoundsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing required parameter &apos;brandId&apos; when calling BrandingApi-&amp;gt;DeleteBrand.
        /// </summary>
        internal static string BrandIdDelete {
            get {
                return ResourceManager.GetString("BrandIdDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing required parameter &apos;brandId&apos; when calling BrandingApi-&amp;gt;GetBrand.
        /// </summary>
        internal static string BrandIdGet {
            get {
                return ResourceManager.GetString("BrandIdGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing required parameter &apos;brandId&apos; when calling BrandingApi-&amp;gt;ResetDefaultBrand.
        /// </summary>
        internal static string BrandIdResetDefault {
            get {
                return ResourceManager.GetString("BrandIdResetDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Brand logo is required.
        /// </summary>
        internal static string BrandLogoRequired {
            get {
                return ResourceManager.GetString("BrandLogoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Brand name is required.
        /// </summary>
        internal static string BrandNameRequired {
            get {
                return ResourceManager.GetString("BrandNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing required parameter &apos;contactId&apos; when calling ContactingApi-&gt;DeleteContact.
        /// </summary>
        internal static string ContactIdDelete {
            get {
                return ResourceManager.GetString("ContactIdDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing required parameter &apos;id&apos; when calling ContactingApi-&gt;UpdateContact.
        /// </summary>
        internal static string ContactIdMissing {
            get {
                return ResourceManager.GetString("ContactIdMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new expiry date must not be less than the current date and time.
        /// </summary>
        internal static string DefaultNewExpiryDate {
            get {
                return ResourceManager.GetString("DefaultNewExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing required parameter &apos;documentId&apos; when calling DocumentApi-&gt;ExtendExpiry.
        /// </summary>
        internal static string DocumentIdAccessCode {
            get {
                return ResourceManager.GetString("DocumentIdAccessCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing required parameter &apos;documentId&apos; when calling IdVerificationApi-&amp;gt;GetImage.
        /// </summary>
        internal static string DocumentIdImage {
            get {
                return ResourceManager.GetString("DocumentIdImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing required parameter &apos;documentId&apos; when calling IdVerificationApi-&amp;gt;GetReport.
        /// </summary>
        internal static string DocumentIdReport {
            get {
                return ResourceManager.GetString("DocumentIdReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document ID is required.
        /// </summary>
        internal static string DocumentIdRequired {
            get {
                return ResourceManager.GetString("DocumentIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing required parameter &apos;documentId&apos; when calling DocumentApi-&gt;AddAuthentication.
        /// </summary>
        internal static string DocumentIdRequiredAPI {
            get {
                return ResourceManager.GetString("DocumentIdRequiredAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing required parameter &apos;documentId&apos; when calling IdVerificationApi-&amp;gt;CreateEmbeddedVerificationUrl.
        /// </summary>
        internal static string DocumentIdVerificationUrl {
            get {
                return ResourceManager.GetString("DocumentIdVerificationUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document info locale does not match the signer’s locale {0}..
        /// </summary>
        internal static string DocumentInfoLocaleMissing {
            get {
                return ResourceManager.GetString("DocumentInfoLocaleMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to document info is missing for the  signer’s language {0}..
        /// </summary>
        internal static string DocumentInfoMissing {
            get {
                return ResourceManager.GetString("DocumentInfoMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document title is required for document info..
        /// </summary>
        internal static string DocumentTitleRequired {
            get {
                return ResourceManager.GetString("DocumentTitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate options are not allowed for the dropdown list.
        /// </summary>
        internal static string DuplicateDropdownOption {
            get {
                return ResourceManager.GetString("DuplicateDropdownOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate role index are not allowed..
        /// </summary>
        internal static string DuplicateRoleIndex {
            get {
                return ResourceManager.GetString("DuplicateRoleIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Date Format is required for Editable Date Field..
        /// </summary>
        internal static string EditableDateFormatRequired {
            get {
                return ResourceManager.GetString("EditableDateFormatRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditableDateFieldSettings shouldn&apos;t be null.
        /// </summary>
        internal static string EditableDateInformationRequired {
            get {
                return ResourceManager.GetString("EditableDateInformationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email ID is a required property and cannot be null or empty.
        /// </summary>
        internal static string EmailIdRequired {
            get {
                return ResourceManager.GetString("EmailIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing required parameter &apos;emailId&apos; when calling DocumentApi-&gt;AddAuthentication.
        /// </summary>
        internal static string EmailIdRequiredAPI {
            get {
                return ResourceManager.GetString("EmailIdRequiredAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter &apos;templateId&apos; should not be null or empty..
        /// </summary>
        internal static string EmbeddedTemplateIdNull {
            get {
                return ResourceManager.GetString("EmbeddedTemplateIdNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be null or empty..
        /// </summary>
        internal static string EmptyFields {
            get {
                return ResourceManager.GetString("EmptyFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label cannot be null or empty.
        /// </summary>
        internal static string EmptyLabels {
            get {
                return ResourceManager.GetString("EmptyLabels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Valid URL.
        /// </summary>
        internal static string EnterValidURL {
            get {
                return ResourceManager.GetString("EnterValidURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multicast delegate for ExceptionFactory is unsupported.
        /// </summary>
        internal static string ExceptionFactoryUnsupported {
            get {
                return ResourceManager.GetString("ExceptionFactoryUnsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided expiry days should be within the range 1 - 180.
        /// </summary>
        internal static string ExpiryDaysValOutOfRange {
            get {
                return ResourceManager.GetString("ExpiryDaysValOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided expiry hours should be within the range 8 - 4320.
        /// </summary>
        internal static string ExpiryHoursValOutOfRange {
            get {
                return ResourceManager.GetString("ExpiryHoursValOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exact date and time given for document expiry should be between 1 to 180 days.
        /// </summary>
        internal static string ExpirySpecifcDateOutOfRange {
            get {
                return ResourceManager.GetString("ExpirySpecifcDateOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one document info is allowed per signer language..
        /// </summary>
        internal static string ExtraLanguageValues {
            get {
                return ResourceManager.GetString("ExtraLanguageValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one document info is allowed per signer locale..
        /// </summary>
        internal static string ExtraLocaleValues {
            get {
                return ResourceManager.GetString("ExtraLocaleValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field description is required.
        /// </summary>
        internal static string FieldDescriptionRequired {
            get {
                return ResourceManager.GetString("FieldDescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field id is required.
        /// </summary>
        internal static string FieldIdRequired {
            get {
                return ResourceManager.GetString("FieldIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field name is required.
        /// </summary>
        internal static string FieldNameRequired {
            get {
                return ResourceManager.GetString("FieldNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fieldType is a required property for FormField and cannot be null.
        /// </summary>
        internal static string FieldTypeRequired {
            get {
                return ResourceManager.GetString("FieldTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing required parameter &apos;fileId&apos; when calling IdVerificationApi-&amp;gt;GetImage.
        /// </summary>
        internal static string FileIdImage {
            get {
                return ResourceManager.GetString("FileIdImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing required parameter &apos;files&apos; when calling DocumentApi-&gt;SendDocument.
        /// </summary>
        internal static string FilesIsSet {
            get {
                return ResourceManager.GetString("FilesIsSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document&apos;s size exceeds the limit of 100 MB. Please replace it. (all files combined).
        /// </summary>
        internal static string FilesizesWithin100MB {
            get {
                return ResourceManager.GetString("FilesizesWithin100MB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The File type for attachment required..
        /// </summary>
        internal static string FileTypeRequired {
            get {
                return ResourceManager.GetString("FileTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form fields value cannot be null or empty..
        /// </summary>
        internal static string FormFieldsRequired {
            get {
                return ResourceManager.GetString("FormFieldsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide group name for radio button form field..
        /// </summary>
        internal static string GroupNameRequired {
            get {
                return ResourceManager.GetString("GroupNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HyperlinkText is required for Hyperlink FormField.
        /// </summary>
        internal static string HyperlinkLabelFieldsRequired {
            get {
                return ResourceManager.GetString("HyperlinkLabelFieldsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is required for Hyperlink FormField.
        /// </summary>
        internal static string HyperlinkValueFieldsRequired {
            get {
                return ResourceManager.GetString("HyperlinkValueFieldsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supported format for the Image is required..
        /// </summary>
        internal static string ImageFormatRequired {
            get {
                return ResourceManager.GetString("ImageFormatRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Image Information is required..
        /// </summary>
        internal static string ImageInformationRequired {
            get {
                return ResourceManager.GetString("ImageInformationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide the Image Title..
        /// </summary>
        internal static string ImageTitleRequired {
            get {
                return ResourceManager.GetString("ImageTitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IImageFile parameter must be an instance of ImageFileStream, ImageFileBytes, or ImageFilePath..
        /// </summary>
        internal static string InvalidBrandFileInstance {
            get {
                return ResourceManager.GetString("InvalidBrandFileInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide a valid brand ID.
        /// </summary>
        internal static string InvalidBrandId {
            get {
                return ResourceManager.GetString("InvalidBrandId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid date format. Supported dateformat is.
        /// </summary>
        internal static string InvalidDateFormat {
            get {
                return ResourceManager.GetString("InvalidDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default option mismatches with the dropdown list of options.
        /// </summary>
        internal static string InvalidDefaultOption {
            get {
                return ResourceManager.GetString("InvalidDefaultOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dropdown option(s) cannot be null or empty.
        /// </summary>
        internal static string InvalidDropdownOption {
            get {
                return ResourceManager.GetString("InvalidDropdownOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide a valid Email ID.
        /// </summary>
        internal static string InvalidEmailAddress {
            get {
                return ResourceManager.GetString("InvalidEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date should be greater or equal to start date..
        /// </summary>
        internal static string InValidEndDate {
            get {
                return ResourceManager.GetString("InValidEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given format is not valid..
        /// </summary>
        internal static string InvalidFormat {
            get {
                return ResourceManager.GetString("InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document info language {0} is not found or used in roles..
        /// </summary>
        internal static string InvalidLanguage {
            get {
                return ResourceManager.GetString("InvalidLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document info locale {0} does not match the one used in roles..
        /// </summary>
        internal static string InvalidLocale {
            get {
                return ResourceManager.GetString("InvalidLocale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signer order should be between 1 and 50..
        /// </summary>
        internal static string InvalidSignerOrder {
            get {
                return ResourceManager.GetString("InvalidSignerOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid field size. Field height and width should be greater then 0..
        /// </summary>
        internal static string InvalidTextTagSize {
            get {
                return ResourceManager.GetString("InvalidTextTagSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labels cannot have more than 255 characters..
        /// </summary>
        internal static string LabelMaxLength {
            get {
                return ResourceManager.GetString("LabelMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any one of the given language is required..
        /// </summary>
        internal static string LanguageRequired {
            get {
                return ResourceManager.GetString("LanguageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max date should be always greater than min date.
        /// </summary>
        internal static string MaxDateValidation {
            get {
                return ResourceManager.GetString("MaxDateValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A document can only contain a maximum of 50 labels.
        /// </summary>
        internal static string MaxLabelsCount {
            get {
                return ResourceManager.GetString("MaxLabelsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A document or template can only contain a maximum of 50 labels.
        /// </summary>
        internal static string MaxTemplateOrDocumentLabelsCount {
            get {
                return ResourceManager.GetString("MaxTemplateOrDocumentLabelsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message exceeds the limit of 5000 characters.
        /// </summary>
        internal static string MessageLengthExceeds {
            get {
                return ResourceManager.GetString("MessageLengthExceeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File input missing. To proceed, please upload a file using the &apos;Files&apos; property or provide a URL for the file using the &apos;FileUrls&apos; property..
        /// </summary>
        internal static string MissingFileInput {
            get {
                return ResourceManager.GetString("MissingFileInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New signer email address is required for changing the recipient details.
        /// </summary>
        internal static string NewSignerEmailAddressRequired {
            get {
                return ResourceManager.GetString("NewSignerEmailAddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role cannot have &apos;FormFields&apos; if no file has been uploaded. Please upload a file before adding &apos;FormFields&apos; for the Role.
        /// </summary>
        internal static string NoRoleFormFieldsWhenNoFile {
            get {
                return ResourceManager.GetString("NoRoleFormFieldsWhenNoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signer cannot have &apos;FormFields&apos; if no file has been uploaded. Please upload a file before adding &apos;FormFields&apos; for the Signer.
        /// </summary>
        internal static string NoSignerFormFieldsWhenNoFile {
            get {
                return ResourceManager.GetString("NoSignerFormFieldsWhenNoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The webhook cannot be processed because the current timestamp is outside of the allowed tolerance.
        /// </summary>
        internal static string NotInAllowedTolerance {
            get {
                return ResourceManager.GetString("NotInAllowedTolerance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The signature for the webhook is not present/matched with the BoldSign-Signature header.
        /// </summary>
        internal static string NotValidSignature {
            get {
                return ResourceManager.GetString("NotValidSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old signer email is required for changing the recipient details.
        /// </summary>
        internal static string OldSignerEmailRequired {
            get {
                return ResourceManager.GetString("OldSignerEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pageNumber is a required property for FormField and cannot be null.
        /// </summary>
        internal static string PageNumberRquired {
            get {
                return ResourceManager.GetString("PageNumberRquired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A reason is required for changing recipient details.
        /// </summary>
        internal static string ReasonRequired {
            get {
                return ResourceManager.GetString("ReasonRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dropdown option(s) are required for the Dropdown form field.
        /// </summary>
        internal static string RequiredDropdownOptions {
            get {
                return ResourceManager.GetString("RequiredDropdownOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is a required parameter to create sender identity..
        /// </summary>
        internal static string RequiredName {
            get {
                return ResourceManager.GetString("RequiredName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviewer should not have any form fields..
        /// </summary>
        internal static string ReviewerFields {
            get {
                return ResourceManager.GetString("ReviewerFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Name is Required..
        /// </summary>
        internal static string RoleName {
            get {
                return ResourceManager.GetString("RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles cannot be null or empty..
        /// </summary>
        internal static string RolesRequired {
            get {
                return ResourceManager.GetString("RolesRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both title and the document information cannot be present for a single document..
        /// </summary>
        internal static string SameProperty {
            get {
                return ResourceManager.GetString("SameProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old and new emails should not be the same.
        /// </summary>
        internal static string SameSignerEmailNotAllowed {
            get {
                return ResourceManager.GetString("SameSignerEmailNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature header can not be null.
        /// </summary>
        internal static string SignatureHeaderIsNull {
            get {
                return ResourceManager.GetString("SignatureHeaderIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New signer name required for changing the recipient details.
        /// </summary>
        internal static string SignerNameRequired {
            get {
                return ResourceManager.GetString("SignerNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signer order should be a positive integer.
        /// </summary>
        internal static string SignerOrderPositiveValue {
            get {
                return ResourceManager.GetString("SignerOrderPositiveValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing required parameter &apos;signers&apos; when calling DocumentApi-&gt;SendDocument.
        /// </summary>
        internal static string SignersIsSet {
            get {
                return ResourceManager.GetString("SignersIsSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom field creation should only be allowed when built-in form fields are enabled. If not, shared custom fields can be enabled..
        /// </summary>
        internal static string StandardFieldVisibilityErr {
            get {
                return ResourceManager.GetString("StandardFieldVisibilityErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing required parameter &apos;teamId&apos; when calling TeamApi-&amp;gt;GetTeamDetails.
        /// </summary>
        internal static string TeamIdIsSet {
            get {
                return ResourceManager.GetString("TeamIdIsSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing required parameter &apos;teamId&apos; when calling TeamApi-&amp;gt;Update.
        /// </summary>
        internal static string TeamIdrequired {
            get {
                return ResourceManager.GetString("TeamIdrequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing required parameter &apos;teamName&apos; when calling TeamApi-&amp;gt;Create.
        /// </summary>
        internal static string TeamNameIsSet {
            get {
                return ResourceManager.GetString("TeamNameIsSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing required parameter &apos;teamName&apos; when calling TeamApi-&amp;gt;Update.
        /// </summary>
        internal static string TeamNameRequired {
            get {
                return ResourceManager.GetString("TeamNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing required parameter &apos;templateId&apos; when calling TemplateApi-&gt;DownloadTemplate.
        /// </summary>
        internal static string TemplateIdDownload {
            get {
                return ResourceManager.GetString("TemplateIdDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing required parameter &apos;templateId&apos; when calling TemplateApi-&gt;GetProperties.
        /// </summary>
        internal static string TemplateIdIsSet {
            get {
                return ResourceManager.GetString("TemplateIdIsSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter {nameof(sendForSignFromTemplate.TemplateId)} should be null or empty.
        /// </summary>
        internal static string TemplateIdNull {
            get {
                return ResourceManager.GetString("TemplateIdNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template ID is required or not in GUID type.
        /// </summary>
        internal static string TemplateIdRequired {
            get {
                return ResourceManager.GetString("TemplateIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template title is required for create template..
        /// </summary>
        internal static string TemplateTitleRequired {
            get {
                return ResourceManager.GetString("TemplateTitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Value property is supported for text tag definitions only for text boxes, labels, drop-downs, hyperlinks, checkboxes, radio buttons, images, and editable date fields..
        /// </summary>
        internal static string TextTagValueNotSupported {
            get {
                return ResourceManager.GetString("TextTagValueNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both title and the document information cannot be present for a single document..
        /// </summary>
        internal static string TitleAndDocumentInfo {
            get {
                return ResourceManager.GetString("TitleAndDocumentInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title exceeds the limit of 256 characters.
        /// </summary>
        internal static string TitleLengthExceeds {
            get {
                return ResourceManager.GetString("TitleLengthExceeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title or Document Information of the document is required..
        /// </summary>
        internal static string TitleOrDocumentInfoIsRequired {
            get {
                return ResourceManager.GetString("TitleOrDocumentInfoIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported file. Supported file formats are PNG, JPEG, JPG and SVG..
        /// </summary>
        internal static string UnsupportedBrandLogoType {
            get {
                return ResourceManager.GetString("UnsupportedBrandLogoType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported file(s). Supported file formats are PDF, Word, PNG, JPEG, JPG and XLSX.
        /// </summary>
        internal static string UnsupportedFileType {
            get {
                return ResourceManager.GetString("UnsupportedFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported Media Type.
        /// </summary>
        internal static string UnsupportedMediaType {
            get {
                return ResourceManager.GetString("UnsupportedMediaType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To update the sender identity, at least one of the following is required: name, notificationSettings, redirectUrl, or metadata..
        /// </summary>
        internal static string UpdateSenderIdentityRequiredFailed {
            get {
                return ResourceManager.GetString("UpdateSenderIdentityRequiredFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID is a required property and cannot be null or empty.
        /// </summary>
        internal static string UserIdRequired {
            get {
                return ResourceManager.GetString("UserIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide valid file URL.
        /// </summary>
        internal static string ValidUrl {
            get {
                return ResourceManager.GetString("ValidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The webhook cannot be processed because the signature cannot be safely calculated.
        /// </summary>
        internal static string WrongSignature {
            get {
                return ResourceManager.GetString("WrongSignature", resourceCulture);
            }
        }
    }
}
