//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoldSign.Api.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApiValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApiValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BoldSign.Api.Resources.ApiValidationMessages", typeof(ApiValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bounds is a required property for FormField and cannot be null.
        /// </summary>
        internal static string BoundsRequired {
            get {
                return ResourceManager.GetString("BoundsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fieldType is a required property for FormField and cannot be null.
        /// </summary>
        internal static string FieldTypeRequired {
            get {
                return ResourceManager.GetString("FieldTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use either Files parameter or FileUrls parameter, but not both.
        /// </summary>
        internal static string FileOrFileUrl {
            get {
                return ResourceManager.GetString("FileOrFileUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document&apos;s size exceeds the limit of 100 MB. Please replace it. (all files combined).
        /// </summary>
        internal static string FilesizesWithin100MB {
            get {
                return ResourceManager.GetString("FilesizesWithin100MB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide a valid brand ID.
        /// </summary>
        internal static string InvalidBrandId {
            get {
                return ResourceManager.GetString("InvalidBrandId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message exceeds the limit of 5000 characters.
        /// </summary>
        internal static string MessageLengthExceeds {
            get {
                return ResourceManager.GetString("MessageLengthExceeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pageNumber is a required property for FormField and cannot be null.
        /// </summary>
        internal static string PageNumberRquired {
            get {
                return ResourceManager.GetString("PageNumberRquired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing required parameter &apos;signers&apos; when calling DocumentApi-&gt;SendDocument.
        /// </summary>
        internal static string SignersIsSet {
            get {
                return ResourceManager.GetString("SignersIsSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter {nameof(sendForSignFromTemplate.TemplateId)} should be null or empty.
        /// </summary>
        internal static string TemplateIdNull {
            get {
                return ResourceManager.GetString("TemplateIdNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing required parameter &apos;title&apos; when calling DocumentApi-&gt;SendDocument.
        /// </summary>
        internal static string TitleIsSet {
            get {
                return ResourceManager.GetString("TitleIsSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title exceeds the limit of 256 characters.
        /// </summary>
        internal static string TitleLengthExceeds {
            get {
                return ResourceManager.GetString("TitleLengthExceeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide valid file URL.
        /// </summary>
        internal static string ValidUrl {
            get {
                return ResourceManager.GetString("ValidUrl", resourceCulture);
            }
        }
    }
}
