// <copyright file="IdVerification.cs" company="Syncfusion Inc">
// Copyright (c) Syncfusion Inc. All rights reserved.
// </copyright>

/*
* BoldSign API
*
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1
*
* Generated by: https://github.com/openapitools/openapi-generator.git
*/

namespace BoldSign.Api.Model.Webhook.IdVerification
{
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    using Newtonsoft.Json;

    /// <summary>
    /// The id verification details.
    /// </summary>
    public class IdVerification
    {
        /// <summary>
        /// Gets or sets the type of id verification.
        /// </summary>
        [DataMember(Name = "type", EmitDefaultValue = false)]
        public string Type { get; set; }

        /// <summary>
        /// Gets or sets the number of retries.
        /// </summary>
        [DataMember(Name = "maximumRetryCount", EmitDefaultValue = false)]
        public int? MaximumRetryCount { get; set; }

        /// <summary>
        /// Gets or sets the status.
        /// </summary>
        [DataMember(Name = "status", EmitDefaultValue = false)]
        public string Status { get; set; }

        /// <summary>
        /// Gets or sets a name matcher.
        /// </summary>
        [DataMember(Name = "nameMatcher", EmitDefaultValue = false)]
        public string NameMatcher { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether require live capture (Disable image file upload).
        /// </summary>
        [DataMember(Name = "requireLiveCapture", EmitDefaultValue = false)]
        public bool? RequireLiveCapture { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether require matching selfie (Selfie and document image should match).
        /// </summary>
        [DataMember(Name = "requireMatchingSelfie", EmitDefaultValue = false)]
        public bool? RequireMatchingSelfie { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether we can hold the signing until sender prefilled form fields.
        /// </summary>
        [DataMember(Name = "holdForPrefill", EmitDefaultValue = false)]
        public bool? HoldForPrefill { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether sender prefilled form fields or not.
        /// </summary>
        [DataMember(Name = "prefillCompleted", EmitDefaultValue = false)]
        public bool? PrefillCompleted { get; set; }

        /// <summary>
        /// Gets or sets the allowed document types of id verification process.
        /// </summary>
        [DataMember(Name = "allowedDocumentTypes", EmitDefaultValue = false)]
        public List<string> AllowedDocumentTypes { get; set; }

        /// <summary>
        /// Returns the JSON string presentation of the object.
        /// </summary>
        /// <returns>JSON string presentation of the object.</returns>
        public virtual string ToJson() => JsonConvert.SerializeObject(this, Formatting.Indented);
    }
}
