// <copyright file="FailedDeliveryMode.cs" company="Syncfusion Inc">
// Copyright (c) Syncfusion Inc. All rights reserved.
// </copyright>

/*
 * BoldSign API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

namespace BoldSign.Api.Model.Webhook
{
    using System.Runtime.Serialization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    /// <summary>
    /// Failed Delivery Mode.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum FailedDeliveryMode
    {
        /// <summary>
        /// Represents Email.
        /// </summary>
        [EnumMember(Value = "Email")]
        Email = 0,

        /// <summary>
        /// Represent SMS.
        /// </summary>
        [EnumMember(Value = "SMS")]
        SMS = 1,

        /// <summary>
        /// Represents WhatsApp.
        /// </summary>
        [EnumMember(Value = "WhatsApp")]
        WhatsApp = 2,
    }
}