/* 
 * BoldSign API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

namespace BoldSign.Model.Webhook
{
    using System;
    using System.Linq;
    using System.IO;
    using System.Text;
    using System.Text.RegularExpressions;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Runtime.Serialization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.ComponentModel.DataAnnotations;

    /// <summary>
    /// The webhook event meta.
    /// </summary>
    [DataContract]
    public class WebhookEventMetadata
    {

        /// <summary>
        /// Gets or sets the webhook event ID.
        /// </summary>
        /// <value>Gets or sets the webhook event ID.</value>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or sets the webhook event created DateTime.
        /// </summary>
        /// <value>Gets or sets the webhook event created DateTime.</value>
        [DataMember(Name = "created", EmitDefaultValue = false)]
        public long? Created { get; set; }

        /// <summary>
        /// Gets or Sets EventType
        /// </summary>
        [DataMember(Name = "eventType", EmitDefaultValue = false)]
        public WebHookEventType EventType { get; set; }

        /// <summary>
        /// Gets or sets application client id.
        /// </summary>
        /// <value>Gets or sets application client id.</value>
        [DataMember(Name = "clientId", EmitDefaultValue = false)]
        public string ClientId { get; set; }

        /// <summary>
        /// Gets or Sets Environment
        /// </summary>
        [DataMember(Name = "environment", EmitDefaultValue = false)]
        public ApplicationEnvironment Environment { get; set; }

    }
}
