// <copyright file="ContactsDetails.cs" company="Syncfusion Inc">
// Copyright (c) Syncfusion Inc. All rights reserved.
// </copyright>

/*
 * BoldSign API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

namespace BoldSign.Model
{
    using System.Runtime.Serialization;

    /// <summary>
    ///     The current page templates view model.
    /// </summary>
    [DataContract]
    public class ContactsDetails
    {
        /// <summary>
        /// Gets or sets the contact id.
        /// </summary>
        [DataMember(Name = "id")]
        public string Id { get; set; }

        /// <summary>
        /// Gets or sets the contact name.
        /// </summary>
        [DataMember(Name = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets the contact email.
        /// </summary>
        [DataMember(Name = "email")]
        public string Email { get; set; }

        /// <summary>
        /// Gets or sets the contact company.
        /// </summary>
        [DataMember(Name = "companyName")]
        public string CompanyName { get; set; }

        /// <summary>
        /// Gets or sets the contact role.
        /// </summary>
        [DataMember(Name = "jobTitle")]
        public string JobTitle { get; set; }

        /// <summary>
        /// Gets or sets the contact phoneNumber.
        /// </summary>
        [DataMember(Name = "phoneNumber")]
        public PhoneNumber PhoneNumber { get; set; }
    }
}
