// <copyright file="CreateTeam.cs" company="Syncfusion Inc">
// Copyright (c) Syncfusion Inc. All rights reserved.
// </copyright>

/*
 * BoldSign API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

namespace BoldSign.Model
{
    using System.Runtime.Serialization;
    using Newtonsoft.Json;

    /// <summary>
    /// create team.
    /// </summary>
    [DataContract(Name = "create")]
    public class CreateTeam
    {
        /// <summary>
        ///  Gets or sets team name.
        /// </summary>
        [JsonProperty("teamName")]
        public string TeamName { get; set; }
    }
}
