// <copyright file="CustomFieldCollection.cs" company="Syncfusion Inc">
// Copyright (c) Syncfusion Inc. All rights reserved.
// </copyright>

/*
* BoldSign API
*
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1
*
* Generated by: https://github.com/openapitools/openapi-generator.git
*/

namespace BoldSign.Model
{
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    /// <summary>
    /// The custom field collection.
    /// </summary>
    [DataContract]
    public class CustomFieldCollection
    {
        /// <summary>
        /// Gets or sets the custom field collection result.
        /// </summary>
        [DataMember(Name = "result", EmitDefaultValue = true)]
        public List<ViewCustomFieldDetails> Result { get; set; }
    }
}
