// <copyright file="CustomFieldMessage.cs" company="Syncfusion Inc">
// Copyright (c) Syncfusion Inc. All rights reserved.
// </copyright>

/*
* BoldSign API
*
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1
*
* Generated by: https://github.com/openapitools/openapi-generator.git
*/

namespace BoldSign.Model
{
    using System.Runtime.Serialization;

    /// <summary>
    /// The custom field message view model.
    /// </summary>
    public class CustomFieldMessage
    {
        /// <summary>
        /// Gets or sets the custom field message.
        /// </summary>
        [DataMember(Name = "message", EmitDefaultValue = true)]
        public string Message { get; set; }

        /// <summary>
        /// Gets or sets the custom field message.
        /// </summary>
        [DataMember(Name = "customFieldId", EmitDefaultValue = true)]
        public string CustomFieldId { get; set; }
    }
}
