/* 
 * BoldSign API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

namespace BoldSign.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Runtime.Serialization;
    using System.Text;
    using Newtonsoft.Json;

    /// <summary>
    ///     The document sender detail includes Email ID, name and so on.
    /// </summary>
    [DataContract]
    public class DocumentSenderDetail
    {
        /// <summary>
        ///     Initializes a new instance of the <see cref="DocumentSenderDetail" /> class.
        /// </summary>
        /// <param name="name">Gets or sets recipient Name..</param>
        /// <param name="emailAddress">Gets or sets the email address..</param>
        /// <param name="userId">Gets or sets the user id..</param>
        /// <param name="isViewed">Gets or sets a value indicating whether is viewed. (default to false).</param>
        public DocumentSenderDetail(string name = default, string emailAddress = default, string userId = default, bool isViewed = false)
        {
            this.Name = name;
            this.EmailAddress = emailAddress;
            this.UserId = userId;
            this.Name = name;
            this.EmailAddress = emailAddress;
            this.UserId = userId;

            // use default value if no "isViewed" provided
            if (isViewed == null)
            {
                this.IsViewed = false;
            }
            else
            {
                this.IsViewed = isViewed;
            }
        }

        /// <summary>
        ///     Gets or sets recipient Name.
        /// </summary>
        /// <value>Gets or sets recipient Name.</value>
        [DataMember(Name = "name", EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        ///     Gets or sets the email address.
        /// </summary>
        /// <value>Gets or sets the email address.</value>
        [DataMember(Name = "emailAddress", EmitDefaultValue = true)]
        public string EmailAddress { get; set; }

        /// <summary>
        ///     Gets or sets the user ID.
        /// </summary>
        /// <value>Gets or sets the user id.</value>
        [DataMember(Name = "userId", EmitDefaultValue = true)]
        public string UserId { get; set; }

        /// <summary>
        ///    Gets or sets a value indicating whether document is viewed.
        /// </summary>
        /// <value>Gets or sets a value indicating whether is viewed.</value>
        [DataMember(Name = "isViewed", EmitDefaultValue = false)]
        public bool IsViewed { get; set; }

        /// <summary>
        ///     Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson() => JsonConvert.SerializeObject(this, Formatting.Indented);
    }
}
