/* 
 * BoldSign API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

namespace BoldSign.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Runtime.Serialization;
    using System.Text;
    using Newtonsoft.Json;

    /// <summary>
    ///     The document files properties include document name, page count.
    /// </summary>
    [DataContract]
    public class DocumentFiles
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DocumentFiles" /> class.
        /// </summary>
        /// <param name="documentName">Gets or Sets DocumentName..</param>
        /// <param name="order">Gets or Sets Order..</param>
        /// <param name="pageCount">Gets or Sets PageCount..</param>
        public DocumentFiles(string documentName = default(string), int? order = default(int?), int? pageCount = default(int?))
        {
            this.DocumentName = documentName;
            this.Order = order;
            this.PageCount = pageCount;
        }

        /// <summary>
        /// Gets or Sets DocumentName.
        /// </summary>
        /// <value>Gets or Sets DocumentName.</value>
        [DataMember(Name = "documentName", EmitDefaultValue = false)]
        public string DocumentName { get; set; }

        /// <summary>
        /// Gets or Sets Order of signers.
        /// </summary>
        /// <value>Gets or Sets Order.</value>
        [DataMember(Name = "order", EmitDefaultValue = false)]
        public int? Order { get; set; }

        /// <summary>
        /// Gets or Sets PageCount for a document file.
        /// </summary>
        /// <value>Gets or Sets PageCount.</value>
        [DataMember(Name = "pageCount", EmitDefaultValue = false)]
        public int? PageCount { get; set; }

        /// <summary>
        /// Gets or Sets TemplateName.
        /// </summary>
        /// <value>Gets the value of templateName.</value>
        [DataMember(Name = "templateName", EmitDefaultValue = false)]
        public string TemplateName { get; set; }

        /// <summary>
        /// Gets or Sets TemplateId.
        /// </summary>
        /// <value>Gets the value of tempalateId.</value>
        [DataMember(Name = "templateId", EmitDefaultValue = false)]
        public string TemplateId { get; set; }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }
    }
}
