/* 
 * BoldSign API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

namespace BoldSign.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.Runtime.Serialization;
    using System.Text;
    using Newtonsoft.Json;

    /// <summary>
    ///     The current page records view model.
    /// </summary>
    [DataContract]
    public class DocumentRecords
    {
        /// <summary>
        ///     Initializes a new instance of the <see cref="DocumentRecords" /> class.
        /// </summary>
        /// <param name="pageDetails">pageDetails.</param>
        /// <param name="result">Gets or sets the documents result..</param>
        public DocumentRecords(PageDetails pageDetails = default, List<Document> result = default)
        {
            this.Result = result;
            this.PageDetails = pageDetails;
            this.Result = result;
        }

        /// <summary>
        ///  Gets or Sets page details
        /// </summary>
        [DataMember(Name = "pageDetails", EmitDefaultValue = false)]
        public PageDetails PageDetails { get; set; }

        /// <summary>
        ///  Gets or sets the document results.
        /// </summary>
        /// <value>Gets or sets the documents result.</value>
        [DataMember(Name = "result", EmitDefaultValue = true)]
        public List<Document> Result { get; set; }

        /// <summary>
        ///     Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson() => JsonConvert.SerializeObject(this, Formatting.Indented);
    }
}
