/* 
 * BoldSign API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

namespace BoldSign.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Runtime.Serialization;
    using System.Text;
    using Newtonsoft.Json;

    /// <summary>
    ///     Document Created Action Result.
    /// </summary>
    [DataContract]
    public class DocumentCreated
    {
        /// <summary>
        ///     Initializes a new instance of the <see cref="DocumentCreated" /> class.
        /// </summary>
        /// <param name="documentId">Gets or sets document ID..</param>
        public DocumentCreated(string documentId = default)
        {
            this.DocumentId = documentId;
            this.DocumentId = documentId;
        }

        /// <summary>
        ///     Gets or sets document ID for a created document.
        /// </summary>
        /// <value>Gets or sets document ID.</value>
        [DataMember(Name = "documentId", EmitDefaultValue = true)]
        public string DocumentId { get; set; }


        /// <summary>
        ///     Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson() => JsonConvert.SerializeObject(this, Formatting.Indented);
    }
}
