/* 
 * BoldSign API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

namespace BoldSign.Model
{
    using System.Runtime.Serialization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    /// <summary>
    ///     Defines DocumentStatus as completed, declined, draft, expired, in progress or revoked.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum DocumentStatus
    {
        /// <summary>
        ///     Enum InProgress for value: InProgress
        /// </summary>
        [EnumMember(Value = "InProgress")]
        InProgress = 1,

        /// <summary>
        ///     Enum Completed for value: Completed
        /// </summary>
        [EnumMember(Value = "Completed")]
        Completed = 2,

        /// <summary>
        ///     Enum Declined for value: Declined
        /// </summary>
        [EnumMember(Value = "Declined")]
        Declined = 3,

        /// <summary>
        ///     Enum Expired for value: Expired
        /// </summary>
        [EnumMember(Value = "Expired")]
        Expired = 4,

        /// <summary>
        ///     Enum Revoked for value: Revoked
        /// </summary>
        [EnumMember(Value = "Revoked")]
        Revoked = 5,

        /// <summary>
        ///     Enum Draft for value: Draft
        /// </summary>
        [EnumMember(Value = "Draft")]
        Draft = 6,
    }
}
