/* 
 * BoldSign API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

namespace BoldSign.Model
{
    using System;
    using System.Linq;
    using System.IO;
    using System.Text;
    using System.Text.RegularExpressions;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Runtime.Serialization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.ComponentModel.DataAnnotations;
    using BoldSign.Api.Model;

    /// <summary>
    /// The document form fields properties include, font, font color, font size and so on.
    /// </summary>
    [DataContract]
    public partial class DocumentFormFields
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DocumentFormFields" /> class.
        /// </summary>
        /// <param name="id">Gets or sets the id..</param>
        /// <param name="type">Gets or sets the element type..</param>
        /// <param name="label">Gets or sets the element type..</param>
        /// <param name="value">Gets or sets the element type..</param>
        /// <param name="font">Gets or sets the element type..</param>
        /// <param name="isRequired">Gets or sets a value indicating whether is required..</param>
        /// <param name="lineHeight">Gets or sets the line height..</param>
        /// <param name="fontSize">Gets or sets the font size..</param>
        /// <param name="fontColor">Gets or sets the font color..</param>
        /// <param name="isUnderline">Gets or sets a value indicating whether isUnderline..</param>
        /// <param name="isItalic">Gets or sets a value indicating whether isItalic..</param>
        /// <param name="isBold">Gets or sets a value indicating whether isBold..</param>
        /// <param name="placeholder">Gets or sets the placeHolder value..</param>
        /// <param name="dateFormat">Gets or sets the dateFormat value..</param>
        /// <param name="validationType">Gets or sets the textbox ValidationType value..</param>
        /// <param name="validationCustomRegex">Gets or sets the textbox ValidationCustomRegex value..</param>
        /// <param name="validationCustomRegexMessage">Gets or sets the textbox ValidationCustomRegexMessage value..</param>
        /// <param name="imageInfo">Gets or sets the imageField.</param>
        /// <param name="attachmentInfo">Gets or sets the attachmentField.</param>
        /// <param name="editableDateFieldSettings">Gets or sets the editableDateFieldSettings.</param>
        public DocumentFormFields(string id = default(string), string type = default(string), string value = default(string), string font = default(string), bool? isRequired = default(bool?), float? lineHeight = default(float?), float? fontSize = default(float?), string fontColor = default(string), bool? isUnderline = default(bool?), bool? isItalic = default(bool?), bool? isBold = default(bool?), string placeholder = default(string), string dateFormat = default(string), ValidationType validationType = default(ValidationType), string validationCustomRegex = default(string), string validationCustomRegexMessage = default(string), ImageInfo imageInfo = default(ImageInfo), AttachmentInfo attachmentInfo = default(AttachmentInfo), EditableDateFieldSettings editableDateFieldSettings = default(EditableDateFieldSettings))
        {
            this.Id = id;
            this.Type = type;
            this.Value = value;
            this.Font = font;
            this.IsRequired = isRequired;
            this.LineHeight = lineHeight;
            this.FontSize = fontSize;
            this.FontColor = fontColor;
            this.IsUnderline = isUnderline;
            this.IsItalic = isItalic;
            this.IsBold = isBold;
            this.Placeholder = placeholder;
            this.DateFormat = dateFormat;
            this.ValidationType = validationType;
            this.ValidationCustomRegex = validationCustomRegex;
            this.ValidationCustomRegexMessage = validationCustomRegexMessage;
            this.ImageInfo = imageInfo;
            this.AttachmentInfo = attachmentInfo;
            this.EditableDateFieldSettings = editableDateFieldSettings;
        }

        /// <summary>
        /// Gets or sets the Id.
        /// </summary>
        /// <value>Gets or sets the id.</value>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or sets the element type.
        /// </summary>
        /// <value>Gets or sets the element type.</value>
        [DataMember(Name = "type", EmitDefaultValue = false)]
        public string Type { get; set; }

        /// <summary>
        /// Gets or sets the element type.
        /// </summary>
        /// <value>Gets or sets the element type.</value>
        [DataMember(Name = "value", EmitDefaultValue = false)]
        public string Value { get; set; }

        /// <summary>
        /// Gets or sets the Font type among the three available types courier, helvetica, times new roman.
        /// </summary>
        /// <value>Gets or sets the element type.</value>
        [DataMember(Name = "font", EmitDefaultValue = false)]
        public string Font { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether is required.
        /// </summary>
        /// <value>Gets or sets a value indicating whether is required.</value>
        [DataMember(Name = "isRequired", EmitDefaultValue = false)]
        public bool? IsRequired { get; set; }

        /// <summary>
        /// Gets or sets the line height for the content in form fields such as text box.
        /// </summary>
        /// <value>Gets or sets the line height.</value>
        [DataMember(Name = "lineHeight", EmitDefaultValue = false)]
        public float? LineHeight { get; set; }

        /// <summary>
        /// Gets or sets the font size.
        /// </summary>
        /// <value>Gets or sets the font size.</value>
        [DataMember(Name = "fontSize", EmitDefaultValue = false)]
        public float? FontSize { get; set; }

        /// <summary>
        /// Gets or sets the font color.
        /// </summary>
        /// <value>Gets or sets the font color.</value>
        [DataMember(Name = "fontColor", EmitDefaultValue = false)]
        public string FontColor { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether isUnderline.
        /// </summary>
        /// <value>Gets or sets a value indicating whether isUnderline.</value>
        [DataMember(Name = "isUnderline", EmitDefaultValue = false)]
        public bool? IsUnderline { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether isItalic.
        /// </summary>
        /// <value>Gets or sets a value indicating whether isItalic.</value>
        [DataMember(Name = "isItalic", EmitDefaultValue = false)]
        public bool? IsItalic { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether isBold.
        /// </summary>
        /// <value>Gets or sets a value indicating whether isBold.</value>
        [DataMember(Name = "isBold", EmitDefaultValue = false)]
        public bool? IsBold { get; set; }

        /// <summary>
        ///     Gets or sets the group name of a radio field.
        /// </summary>
        /// <value>Gets or sets the name.</value>
        [DataMember(Name = "groupName", EmitDefaultValue = true)]
        public string GroupName { get; set; }

        /// <summary>
        /// Gets or sets the placeHolder value.
        /// </summary>
        /// <value>Gets or sets the element type.</value>
        [DataMember(Name = "placeholder", EmitDefaultValue = false)]
        public string Placeholder { get; set; }

        /// <summary>
        /// Gets or sets the DateFormat value.
        /// </summary>
        /// <value>Gets or sets the DateFormat value.</value>
        [DataMember(Name = "dateFormat", EmitDefaultValue = false)]
        public string DateFormat { get; set; }

        /// <summary>
        /// Gets or sets the textbox ValidationType value.
        /// </summary>
        [DataMember(Name = "validationType", EmitDefaultValue = false)]
        public ValidationType ValidationType { get; set; }

        /// <summary>
        /// Gets or sets the text ValidationCustomRegex value.
        /// </summary>
        [DataMember(Name = "validationCustomRegex", EmitDefaultValue = false)]
        public string ValidationCustomRegex { get; set; }

        /// <summary>
        /// Gets or sets the text ValidationCustomRegexMessage value.
        /// </summary>
        [DataMember(Name = "validationCustomRegexMessage", EmitDefaultValue = false)]
        public string ValidationCustomRegexMessage { get; set; }

        /// <summary>
        /// Gets or sets the Image Information. .
        /// </summary>
        [DataMember(Name = "imageInfo", EmitDefaultValue = false)]
        public ImageInfo ImageInfo { get; set; }

        /// <summary>
        /// Gets or sets the Attachment Information. .
        /// </summary>
        [DataMember(Name = "attachmentInfo", EmitDefaultValue = false)]
        public AttachmentInfo AttachmentInfo { get; set; }

        /// <summary>
        /// Gets or sets the EditableDateFieldSettings Information. .
        /// </summary>
        [DataMember(Name = "editableDateFieldSettings", EmitDefaultValue = false)]
        public EditableDateFieldSettings EditableDateFieldSettings { get; set; }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }
    }
}
