// <copyright file="EmailSignedDocument.cs" company="Syncfusion Inc">
// Copyright (c) Syncfusion Inc. All rights reserved.
// </copyright>

/*
 * BoldSign API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

namespace BoldSign.Model
{
    using System.Runtime.Serialization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    /// <summary>
    ///     Represents email signed document.
    /// </summary>
    /// <value>Represents the email signed document.</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum EmailSignedDocument
    {
        /// <summary>
        /// Attachment type.
        /// </summary>
        Attachment = 1,

        /// <summary>
        /// Document link in email type.
        /// </summary>
        DocumentLink = 2,
    }
}
