// <copyright file="EmbeddedSendCreated.cs" company="Syncfusion Inc">
// Copyright (c) Syncfusion Inc. All rights reserved.
// </copyright>

/*
 * BoldSign API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

namespace BoldSign.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Runtime.Serialization;
    using System.Text;

    using Newtonsoft.Json;

    /// <summary>
    ///     Embedded send document created result.
    /// </summary>
    [DataContract]
    public class EmbeddedSendCreated
    {
        /// <summary>
        ///     Initializes a new instance of the <see cref="EmbeddedSendCreated" /> class.
        /// </summary>
        /// <param name="documentId">Gets or sets document ID..</param>
        public EmbeddedSendCreated(string documentId = default)
        {
            this.DocumentId = documentId;
        }

        /// <summary>
        ///     Gets or sets document ID for a created document.
        /// </summary>
        /// <value>Gets or sets document ID.</value>
        [DataMember(Name = "documentId", EmitDefaultValue = true)]
        public string DocumentId { get; set; }

        /// <summary>
        ///     Gets or sets document send url.
        /// </summary>
        /// <value>Gets or sets document ID.</value>
        [DataMember(Name = "sendUrl", EmitDefaultValue = true)]
        public Uri SendUrl { get; set; }

        /// <summary>
        ///     Returns the JSON string presentation of the object.
        /// </summary>
        /// <returns>JSON string presentation of the object.</returns>
        public virtual string ToJson() => JsonConvert.SerializeObject(this, Formatting.Indented);
    }
}
