/*
 * BoldSign API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

namespace BoldSign.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.IO;
    using System.Runtime.Serialization;
    using System.Text;
    using Newtonsoft.Json;

    /// <summary>
    ///     The form field properties include character limit, font, font size, and so on.
    /// </summary>
    [DataContract]
    public class FormField
    {
        /// <summary>
        ///     Initializes a new instance of the <see cref="FormField" /> class.
        /// </summary>
        [JsonConstructor]
        protected FormField()
        {
        }

        /// <summary>
        ///     Initializes a new instance of the <see cref="FormField" /> class.
        /// </summary>
        /// <param name="name">Gets or sets the name..</param>
        /// <param name="type">fieldType (required).</param>
        /// <param name="pageNumber">Gets or sets the page number. (required).</param>
        /// <param name="bounds">bounds (required).</param>
        /// <param name="isRequired">Gets or sets a value indicating whether is required..</param>
        /// <param name="value">Gets or sets the value..</param>
        public FormField(string name = default, FieldType type = default, int pageNumber = default, Rectangle bounds = default, bool isRequired = default, string value = default, FontFamily font = FontFamily.Helvetica,  int fontSize = default, string fontHexColor = default, bool isBoldFont = default, bool isItalicFont = default, bool isUnderLineFont = default, int lineHeight = default, int characterLimit = default, string groupName = default)
        {

            // to ensure "fieldType" is required (not null)
            if (type == null)
            {
                throw new InvalidDataException("fieldType is a required property for FormField and cannot be null");
            }

            this.Type = type;

            // to ensure "pageNumber" is required (not null)
            if (pageNumber == null)
            {
                throw new InvalidDataException("pageNumber is a required property for FormField and cannot be null");
            }

            this.PageNumber = pageNumber;

            // to ensure "bounds" is required (not null)
            if (bounds == null)
            {
                throw new InvalidDataException("bounds is a required property for FormField and cannot be null");
            }

            this.Bounds = bounds;

            this.Value = value;
            this.Name = name;
            this.IsRequired = isRequired;
            this.FontHexColor = fontHexColor;
            this.IsBoldFont = isBoldFont;
            this.IsItalicFont = isItalicFont;
            this.IsUnderLineFont = isUnderLineFont;
            this.LineHeight = lineHeight;
            this.CharacterLimit = characterLimit;
            this.GroupName = groupName;
            this.Font = font;
            this.FontSize = fontSize;
        }

        /// <summary>
        ///     Gets or Sets form field type.
        /// </summary>
        [DataMember(Name = "fieldType", EmitDefaultValue = true)]
        public FieldType Type { get; set; }

        /// <summary>
        ///     Gets or Sets font name for the content in form field.
        /// </summary>
        [DataMember(Name = "font", EmitDefaultValue = true)]
        public FontFamily Font { get; set; }

        /// <summary>
        ///     Gets or sets the font color in hex code.
        /// </summary>
        /// <value>Gets or sets the name.</value>
        [DataMember(Name = "fontHexColor", EmitDefaultValue = true)]
        public string FontHexColor { get; set; }

        /// <summary>
        ///     Gets or sets the form field name.
        /// </summary>
        /// <value>Gets or sets the name.</value>
        [DataMember(Name = "name", EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        ///     Gets or sets the page number.
        /// </summary>
        /// <value>Gets or sets the page number.</value>
        [DataMember(Name = "pageNumber", EmitDefaultValue = true)]
        public int PageNumber { get; set; }

        /// <summary>
        ///     Gets or sets the font size.
        /// </summary>
        /// <value>Gets or sets the page number.</value>
        [DataMember(Name = "fontSize", EmitDefaultValue = true)]
        public int FontSize { get; set; }

        /// <summary>
        ///     Gets or sets a value indicating whether the font style is bold.
        /// </summary>
        /// <value>Gets or sets a value indicating whether is required.</value>
        [DataMember(Name = "isBoldFont", EmitDefaultValue = false)]
        public bool IsBoldFont { get; set; }

        /// <summary>
        ///     Gets or sets a value indicating whether the font style is italic.
        /// </summary>
        /// </summary>
        /// <value>Gets or sets a value indicating whether is required.</value>
        [DataMember(Name = "isItalicFont", EmitDefaultValue = false)]
        public bool IsItalicFont { get; set; }

        /// <summary>
        ///     Gets or sets a value indicating whether the font style is underline.
        /// </summary>
        /// <value>Gets or sets a value indicating whether is required.</value>
        [DataMember(Name = "isUnderLineFont", EmitDefaultValue = false)]
        public bool IsUnderLineFont { get; set; }

        /// <summary>
        ///     Gets or Sets bounds of the form field.
        /// </summary>
        [DataMember(Name = "bounds", EmitDefaultValue = true)]
        public Rectangle Bounds { get; set; }

        /// <summary>
        ///     Gets or sets a value indicating whether the field is required.
        /// </summary>
        /// <value>Gets or sets a value indicating whether is required.</value>
        [DataMember(Name = "isRequired", EmitDefaultValue = false)]
        public bool IsRequired { get; set; }

        /// <summary>
        ///     Gets or sets the Value to be set to the form field (if required).
        /// </summary>
        /// <value>Gets or sets the value.</value>
        [DataMember(Name = "value", EmitDefaultValue = true)]
        public string Value { get; set; }

        /// <summary>
        ///     Gets or sets the line height for the contents in form field.
        /// </summary>
        /// <value>Gets or sets the page number.</value>
        [DataMember(Name = "lineHeight", EmitDefaultValue = true)]
        public int LineHeight { get; set; }

        /// <summary>
        ///     Gets or sets the character limit.
        /// </summary>
        /// <value>Gets or sets the line height.</value>
        [DataMember(Name = "characterLimit", EmitDefaultValue = true)]
        public int CharacterLimit { get; set; }

        /// <summary>
        ///     Gets or sets the group name for the radio field.
        /// </summary>
        /// <value>Gets or sets the name.</value>
        [DataMember(Name = "groupName", EmitDefaultValue = true)]
        public string GroupName { get; set; }

        /// <summary>
        ///     Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson() => JsonConvert.SerializeObject(this, Formatting.Indented);
    }
}
