// <copyright file="FormulaFieldSettings.cs" company="Syncfusion Inc">
// Copyright (c) Syncfusion Inc. All rights reserved.
// </copyright>

namespace BoldSign.Model
{
    /*
 * BoldSign API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

    using System.Runtime.Serialization;

    /// <summary>
    /// Formula Field Settings.
    /// </summary>
    [DataContract]
    public class FormulaFieldSettings
    {
        /// <summary>
        /// Gets or sets the formula expression.
        /// </summary>
        [DataMember(Name = "formulaExpression", EmitDefaultValue = false)]
        public string FormulaExpression { get; set; }

        /// <summary>
        /// Gets or sets the round precision.
        /// </summary>
        [DataMember(Name = "decimalPrecision", EmitDefaultValue = false)]
        public int DecimalPrecision { get; set; }
    }
}
