// <copyright file="KbaSettings.cs" company="Syncfusion Inc">
// Copyright (c) Syncfusion Inc. All rights reserved.
// </copyright>

/*
* BoldSign API
*
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1
*
* Generated by: https://github.com/openapitools/openapi-generator.git
*/

namespace BoldSign.Model
{
    using System.Runtime.Serialization;
    using BoldSign.Api.Model;
    using BoldSign.Api.Model.Kba;
    using Newtonsoft.Json;

    /// <summary>
    /// The KBA settings.
    /// </summary>
    [DataContract]
    public class KbaSettings
    {
        /// <summary>
        /// Gets or sets the authentication frequency.
        /// </summary>
        [DataMember(Name = "type", EmitDefaultValue = false)]
        [JsonProperty("type")]
        public AuthenticationFrequency? Type { get; set; }

        /// <summary>
        /// Gets or sets the maximum retry count.
        /// </summary>
        [DataMember(Name = "maximumRetryCount", EmitDefaultValue = false)]
        [JsonProperty("maximumRetryCount")]
        public int? MaximumRetryCount { get; set; }

        /// <summary>
        /// Gets or sets the name matching level.
        /// </summary>
        [DataMember(Name = "nameMatcher", EmitDefaultValue = false)]
        [JsonProperty("nameMatcher")]
        public KbaNameMatchLevel? NameMatcher { get; set; }

        /// <summary>
        /// Returns the JSON string presentation of the object.
        /// </summary>
        /// <returns>JSON string presentation of the object.</returns>
        public virtual string ToJson() => JsonConvert.SerializeObject(this, Formatting.Indented);
    }
}
