// <copyright file="SignatureFrameSettings.cs" company="Syncfusion Inc">
// Copyright (c) Syncfusion Inc. All rights reserved.
// </copyright>

/*
 * BoldSign API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

namespace BoldSign.Api.Model
{
    using System.Runtime.Serialization;

    /// <summary>
    /// The Signature Frame Settings.
    /// </summary>
    public class SignatureFrameSettings
    {
        /// <summary>
        /// Gets or sets a value indicating whether the signature frame around the signature is enabled.
        /// </summary>
        [DataMember(Name = "enableSignatureFrame", EmitDefaultValue = false)]
        public bool EnableSignatureFrame { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether show signer's full name.
        /// </summary>]
        [DataMember(Name = "showRecipientName", EmitDefaultValue = false)]
        public bool ShowRecipientName { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether show signer's email address.
        /// </summary>
        [DataMember(Name = "showRecipientEmail", EmitDefaultValue = false)]
        public bool ShowRecipientEmail { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether show date and time when the document was signed.
        /// </summary>
        [DataMember(Name = "showTimeStamp", EmitDefaultValue = false)]
        public bool ShowTimeStamp { get; set; }
    }
}
