// <copyright file="SignType.cs" company="Syncfusion Inc">
// Copyright (c) Syncfusion Inc. All rights reserved.
// </copyright>

/*
 * BoldSign API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

namespace BoldSign.Model
{
    using System.Runtime.Serialization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    /// <summary>
    /// Represents the sign type.
    /// </summary>
    /// <value>Represents SignType. Defaults to Single</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum SignType
    {
#pragma warning disable CA1720 // Identifier contains type name
        /// <summary>
        /// Enum Single for value: Single
        /// </summary>
        [EnumMember(Value = "Single")]
        Single = 0,
#pragma warning restore CA1720 // Identifier contains type name

        /// <summary>
        /// Enum Group for value: Group
        /// </summary>
        [EnumMember(Value = "Group")]
        Group = 1,
    }
}