// <copyright file="Size.cs" company="Syncfusion Inc">
// Copyright (c) Syncfusion Inc. All rights reserved.
// </copyright>

/*
 * BoldSign API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

namespace BoldSign.Model
{
    using System.Runtime.Serialization;
    using Newtonsoft.Json;

    /// <summary>
    ///     The rectangle properties are height, width, and so on.
    /// </summary>
    [DataContract]
    public class Size
    {
        /// <summary>
        ///     Initializes a new instance of the <see cref="Size" /> class.
        /// </summary>
        /// <param name="width">Gets or sets the width. (default to 35F).</param>
        /// <param name="height">Gets or sets the height. (default to 16F).</param>
        public Size(float width = 35F, float height = 16F)
        {
            // use default value if no "width" provided
            this.Width = width;
            this.Height = height;
        }

        /// <summary>
        ///     Gets or sets the width of rectangle.
        /// </summary>
        /// <value>Gets or sets the width.</value>
        [DataMember(Name = "width", EmitDefaultValue = false)]
        public float Width { get; set; }

        /// <summary>
        ///     Gets or sets the height of rectangle.
        /// </summary>
        /// <value>Gets or sets the height.</value>
        [DataMember(Name = "height", EmitDefaultValue = false)]
        public float Height { get; set; }

        /// <summary>
        ///     Returns the JSON string presentation of the object.
        /// </summary>
        /// <returns>JSON string presentation of the object.</returns>
        public virtual string ToJson() => JsonConvert.SerializeObject(this, Formatting.Indented);
    }
}
