// <copyright file="TemplateFiles.cs" company="Syncfusion Inc">
// Copyright (c) Syncfusion Inc. All rights reserved.
// </copyright>

/*
 * BoldSign API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

namespace BoldSign.Model
{
    using System.Runtime.Serialization;
    using Newtonsoft.Json;

    /// <summary>
    ///     The document files properties include document name, page count.
    /// </summary>
    [DataContract]
    public class TemplateFiles
    {
        /// <summary>
        /// Gets or sets the file id.
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets DocumentName.
        /// </summary>
        /// <value>Gets the value of DocumentName.</value>
        [DataMember(Name = "documentName", EmitDefaultValue = false)]
        public string DocumentName { get; set; }

        /// <summary>
        /// Gets or Sets Order of signers.
        /// </summary>
        /// <value>Gets or Sets Order.</value>
        [DataMember(Name = "order", EmitDefaultValue = false)]
        public int? Order { get; set; }

        /// <summary>
        /// Gets or Sets PageCount for a document file.
        /// </summary>
        /// <value>Gets or Sets PageCount.</value>
        [DataMember(Name = "pageCount", EmitDefaultValue = false)]
        public int? PageCount { get; set; }

        /// <summary>
        /// Returns the JSON string presentation of the object.
        /// </summary>
        /// <returns>JSON string presentation of the object.</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }
    }
}
