/* 
 * BoldSign API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

namespace BoldSign.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Runtime.Serialization;
    using System.Text;
    using Newtonsoft.Json;

    /// <summary>
    ///     The template document sender user details have functions that define the email address, name of user ID of the recipient.
    /// </summary>
    [DataContract]
    public class TemplateSenderDetails
    {
        /// <summary>
        ///     Initializes a new instance of the <see cref="TemplateSenderDetails" /> class.
        /// </summary>
        /// <param name="name">Gets or sets recipient Name..</param>
        /// <param name="emailAddress">Gets or sets recipient Email address..</param>
        /// <param name="userId">Gets or sets recipient User Id..</param>
        public TemplateSenderDetails(string name = default, string emailAddress = default, string userId = default)
        {
            this.Name = name;
            this.EmailAddress = emailAddress;
            this.UserId = userId;
            this.Name = name;
            this.EmailAddress = emailAddress;
            this.UserId = userId;
        }

        /// <summary>
        ///     Gets or sets recipient Name.
        /// </summary>
        /// <value>Gets or sets recipient Name.</value>
        [DataMember(Name = "name", EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        ///     Gets or sets recipient Email address.
        /// </summary>
        /// <value>Gets or sets recipient Email address.</value>
        [DataMember(Name = "emailAddress", EmitDefaultValue = true)]
        public string EmailAddress { get; set; }

        /// <summary>
        ///     Gets or sets recipient User Id.
        /// </summary>
        /// <value>Gets or sets recipient User Id.</value>
        [DataMember(Name = "userId", EmitDefaultValue = true)]
        public string UserId { get; set; }

        /// <summary>
        ///     Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson() => JsonConvert.SerializeObject(this, Formatting.Indented);
    }
}
