// <copyright file="UserStatus.cs" company="Syncfusion Inc">
// Copyright (c) Syncfusion Inc. All rights reserved.
// </copyright>

/*
 * BoldSign API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

namespace BoldSign.Model
{
    using System.Runtime.Serialization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    /// <summary>
    ///     Defines UserStatus as Active, InvitationPending, Deactivated.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum UserStatus
    {
        /// <summary>
        ///     Enum Active for value: Active
        /// </summary>
        [EnumMember(Value = "Active")]
        Active = 1,

        /// <summary>
        ///     Enum InvitationPending for value:InvitationPending
        /// </summary>
        [EnumMember(Value = "InvitationPending")]
        InvitationPending = 2,

        /// <summary>
        ///     Enum Deactivated for value: Deactivated
        /// </summary>
        [EnumMember(Value = "Deactivated")]
        Deactivated = 3,
    }
}
