// <copyright file="Address.cs" company="Syncfusion Inc">
// Copyright (c) Syncfusion Inc. All rights reserved.
// </copyright>

/*
 * BoldSign API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

namespace BoldSign.Model.IdVerification
{
    using System.Runtime.Serialization;
    using Newtonsoft.Json;

    /// <summary>
    /// The address details.
    /// </summary>
    [DataContract]
    public class Address
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Address" /> class.
        /// </summary>
        /// <param name="city">Gets or sets the city.</param>
        /// <param name="country">Gets or sets the country.</param>
        /// <param name="line1">Gets or sets the line1.</param>
        /// <param name="line2">Gets or sets the line2.</param>
        /// <param name="postalCode">Gets or sets the postal code.</param>
        /// <param name="state">Gets or sets the state.</param>
        public Address(
            string city = default,
            string country = default,
            string line1 = default,
            string line2 = default,
            string postalCode = default,
            string state = default)
        {
            this.City = city;
            this.Country = country;
            this.Line1 = line1;
            this.Line2 = line2;
            this.PostalCode = postalCode;
            this.State = state;
        }

        /// <summary>
        /// Gets or sets the city.
        /// </summary>
        [DataMember(Name = "city", EmitDefaultValue = false)]
        public string City { get; set; }

        /// <summary>
        /// Gets or sets the country.
        /// </summary>
        [DataMember(Name = "country", EmitDefaultValue = false)]
        public string Country { get; set; }

        /// <summary>
        /// Gets or sets the line1.
        /// </summary>
        [DataMember(Name = "line1", EmitDefaultValue = false)]
        public string Line1 { get; set; }

        /// <summary>
        /// Gets or sets the line2.
        /// </summary>
        [DataMember(Name = "line2", EmitDefaultValue = false)]
        public string Line2 { get; set; }

        /// <summary>
        /// Gets or sets the postal code.
        /// </summary>
        [DataMember(Name = "postalCode", EmitDefaultValue = false)]
        public string PostalCode { get; set; }

        /// <summary>
        /// Gets or sets the state.
        /// </summary>
        [DataMember(Name = "state", EmitDefaultValue = false)]
        public string State { get; set; }

        /// <summary>
        /// Returns the JSON string presentation of the object.
        /// </summary>
        /// <returns>JSON string presentation of the object.</returns>
        public virtual string ToJson() => JsonConvert.SerializeObject(this, Formatting.Indented);
    }
}
