// <copyright file="IdDocument.cs" company="Syncfusion Inc">
// Copyright (c) Syncfusion Inc. All rights reserved.
// </copyright>

/*
 * BoldSign API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

namespace BoldSign.Model.IdVerification
{
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    using Newtonsoft.Json;

    /// <summary>
    /// The id verification document details.
    /// </summary>
    [DataContract]
    public class IdDocument
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="IdDocument" /> class.
        /// </summary>
        /// <param name="type">Gets or sets the type.</param>
        /// <param name="firstName">Gets or sets the first name.</param>
        /// <param name="lastName">Gets or sets the last name.</param>
        /// <param name="country">Gets or sets the country.</param>
        /// <param name="documentNumber">Gets or sets the document number.</param>
        /// <param name="address">Gets or sets the address.</param>
        /// <param name="dob">Gets or sets the date of birth.</param>
        /// <param name="issuedDate">Gets or sets the issued date.</param>
        /// <param name="expirationDate">Gets or sets the expiration date.</param>
        /// <param name="documentFiles">Gets or sets the document files.</param>
        /// <param name="selfieFile">Gets or sets the selfie file.</param>
        public IdDocument(
            string type = default,
            string firstName = default,
            string lastName = default,
            string country = default,
            string documentNumber = default,
            Address address = default,
            Date dob = default,
            Date issuedDate = default,
            Date expirationDate = default,
            List<string> documentFiles = default,
            string selfieFile = default)
        {
            this.Type = type;
            this.FirstName = firstName;
            this.LastName = lastName;
            this.Country = country;
            this.DocumentNumber = documentNumber;
            this.Address = address;
            this.Dob = dob;
            this.IssuedDate = issuedDate;
            this.ExpirationDate = expirationDate;
            this.DocumentFiles = documentFiles;
            this.SelfieFile = selfieFile;
        }

        /// <summary>
        /// Gets or sets the type.
        /// </summary>
        [DataMember(Name = "type", EmitDefaultValue = false)]
        public string Type { get; set; }

        /// <summary>
        /// Gets or sets the first name.
        /// </summary>
        [DataMember(Name = "firstName", EmitDefaultValue = false)]
        public string FirstName { get; set; }

        /// <summary>
        /// Gets or sets the last name.
        /// </summary>
        [DataMember(Name = "lastName", EmitDefaultValue = false)]
        public string LastName { get; set; }

        /// <summary>
        /// Gets or sets the country.
        /// </summary>
        [DataMember(Name = "country", EmitDefaultValue = false)]
        public string Country { get; set; }

        /// <summary>
        /// Gets or sets the document number.
        /// </summary>
        [DataMember(Name = "documentNumber", EmitDefaultValue = false)]
        public string DocumentNumber { get; set; }

        /// <summary>
        /// Gets or sets the address.
        /// </summary>
        [DataMember(Name = "address", EmitDefaultValue = false)]
        public Address Address { get; set; }

        /// <summary>
        /// Gets or sets the date of birth.
        /// </summary>
        [DataMember(Name = "dob", EmitDefaultValue = false)]
        public Date Dob { get; set; }

        /// <summary>
        /// Gets or sets the issued date.
        /// </summary>
        [DataMember(Name = "issuedDate", EmitDefaultValue = false)]
        public Date IssuedDate { get; set; }

        /// <summary>
        /// Gets or sets the expiration date.
        /// </summary>
        [DataMember(Name = "expirationDate", EmitDefaultValue = false)]
        public Date ExpirationDate { get; set; }

        /// <summary>
        /// Gets or sets the document files.
        /// </summary>
        [DataMember(Name = "documentFiles", EmitDefaultValue = false)]
        public List<string> DocumentFiles { get; set; }

        /// <summary>
        /// Gets or sets the selfie file.
        /// </summary>
        [DataMember(Name = "selfieFile", EmitDefaultValue = false)]
        public string SelfieFile { get; set; }

        /// <summary>
        /// Returns the JSON string presentation of the object.
        /// </summary>
        /// <returns>JSON string presentation of the object.</returns>
        public virtual string ToJson() => JsonConvert.SerializeObject(this, Formatting.Indented);
    }
}
