// <copyright file="NameVariation.cs" company="Syncfusion Inc">
// Copyright (c) Syncfusion Inc. All rights reserved.
// </copyright>

/*
* BoldSign API
*
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1
*
* Generated by: https://github.com/openapitools/openapi-generator.git
*/

namespace BoldSign.Model.IdVerification
{
    using System.Runtime.Serialization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    /// <summary>
    /// Enum representing the levels of name variation matching.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum NameVariation
    {
        /// <summary>
        /// Represents strict name variation matching.
        /// </summary>
        [EnumMember(Value = "Strict")]
        Strict = 1,

        /// <summary>
        /// Represents moderate name variation matching.
        /// </summary>
        [EnumMember(Value = "Moderate")]
        Moderate = 2,

        /// <summary>
        /// Represents lenient name variation matching.
        /// </summary>
        [EnumMember(Value = "Lenient")]
        Lenient = 3,
    }
}
