// <copyright file="Font.cs" company="Syncfusion Inc">
// Copyright (c) Syncfusion Inc. All rights reserved.
// </copyright>

/*
 * BoldSign API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

namespace BoldSign.Api.Model
{
    using System;
    using BoldSign.Model;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    /// <summary>
    /// The font style.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum FontStyle
    {
        /// <summary>
        /// Regular.
        /// </summary>
        Regular = 0,

        /// <summary>
        /// Bold.
        /// </summary>
        Bold = 1,

        /// <summary>
        /// Italic.
        /// </summary>
        Italic = 2,

        /// <summary>
        /// Underline.
        /// </summary>
        Underline = 4,
    }

    /// <summary>
    /// The font model.
    /// </summary>
    public class Font
    {
        /// <summary>
        /// Gets or sets Name.
        /// </summary>
        public FontFamily? Name { get; set; } = FontFamily.Helvetica;

        /// <summary>
        /// Gets or sets the hex color.
        /// </summary>
        public string Color { get; set; } = "#000000";

        /// <summary>
        /// Gets or sets Size.
        /// </summary>
        public float? Size { get; set; }

        /// <summary>
        /// Gets or sets Style.
        /// </summary>
        [Obsolete("Style is deprecated, please use IsBoldFont, IsItalicFont and IsUnderLineFont.")]
        public FontStyle? Style { get; set; }

        /// <summary>
        /// Gets or sets LineHeight.
        /// </summary>
        public int? LineHeight { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether the font style is bold.
        /// </summary>
        public bool IsBoldFont { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether the font style is italic.
        /// </summary>
        public bool IsItalicFont { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether the font style is underline.
        /// </summary>
        public bool IsUnderLineFont { get; set; }
    }
}
