/*
 * BoldSign API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

namespace BoldSign.Model.Webhook
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    using System.Text;

    /// <summary>
    ///     Send for Sign request DTO.
    /// </summary>
    public class WebhookEvent
    {
        /// <summary>
        /// Gets or sets the webhook event meta data.
        /// </summary>
        [DataMember(Name = "event", EmitDefaultValue = false)]
        public WebhookEventMetadata Event { get; set; }

        /// <summary>
        /// Gets or sets the webhook document event object.
        /// </summary>
        [DataMember(Name = "document", EmitDefaultValue = false)]
        public DocumentEvent Document { get; set; }
    }
}
